# Generated by Django 5.1 on 2025-08-03 00:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('LAND', 'Land'), ('SEA', 'Sea'), ('AIR', 'Air')], max_length=10)),
                ('speed_mph', models.PositiveIntegerField()),
                ('supply_space', models.PositiveIntegerField()),
                ('supply_cost', models.PositiveIntegerField()),
                ('armor_type', models.CharField(choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy'), ('STRUCTURE', 'Structure')], max_length=50)),
                ('damage_type', models.CharField(choices=[('LIGHT', 'Light'), ('MEDIUM', 'Medium'), ('HEAVY', 'Heavy')], max_length=50)),
                ('defense_mod', models.IntegerField()),
                ('health', models.IntegerField()),
                ('is_logi', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('hitpoints', models.PositiveIntegerField()),
                ('primary_ammo', models.IntegerField()),
                ('secondary_ammo', models.IntegerField()),
                ('terciary_ammo', models.IntegerField()),
                ('supplies_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.assettype')),
            ],
        ),
    ]
