# Generated by Django 5.2.4 on 2025-08-04 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('City', 'City'), ('Port', 'Port'), ('Ground Base', 'Ground Base'), ('Airfield', 'Airfield'), ('Supply Node', 'Supply Node'), ('Stockpile', 'Stockpile')], max_length=100, unique=True)),
                ('max_victory_points', models.FloatField()),
                ('can_repair', models.BooleanField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('access_level', models.CharField(choices=[('Strategic', 'Strategic'), ('Operational', 'Operational'), ('Tactical', 'Tactical')], max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.FloatField()),
                ('domain', models.CharField(choices=[('Ground', 'Ground'), ('Air', 'Air'), ('Sea', 'Sea'), ('Logistic', 'Logistic')], max_length=20)),
                ('type', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], max_length=20)),
                ('max_health', models.FloatField()),
                ('speed', models.FloatField()),
                ('supply_space', models.FloatField()),
                ('defense_modifier', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RoleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.team')),
            ],
        ),
        migrations.CreateModel(
            name='LandmarkInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory_points', models.FloatField()),
                ('landmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.landmark')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.team')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('terrain', models.CharField(choices=[('Ocean', 'Ocean'), ('Forest', 'Forest'), ('Jungle/Swamp', 'Jungle/Swamp'), ('Plains/Grasslands', 'Plains/Grasslands'), ('Mountain', 'Mountain'), ('Desert', 'Desert'), ('Urban', 'Urban'), ('Road', 'Road')], max_length=30)),
            ],
            options={
                'unique_together': {('row', 'column')},
            },
        ),
        migrations.CreateModel(
            name='TileInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.landmarkinstance')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.tile')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('to_hit', models.FloatField()),
                ('shots', models.IntegerField()),
                ('min_damage', models.FloatField()),
                ('max_damage', models.FloatField()),
                ('range', models.FloatField()),
                ('type', models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Structure', 'Structure')], max_length=20)),
                ('attack_modifier', models.FloatField()),
                ('attack_modifier_applies_to', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='wargamelogic.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='wargamelogic.unit')),
            ],
        ),
        migrations.CreateModel(
            name='UnitInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.team')),
                ('tile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.tile')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.unit')),
            ],
        ),
    ]
