# Generated by Django 5.2.4 on 2025-08-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='supply_space',
            new_name='max_supply_space',
        ),
        migrations.AddField(
            model_name='unitinstance',
            name='supply_count',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
