# Generated by Django 5.1 on 2025-07-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bradley',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='destroyer',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='f18',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
