# Generated by Django 5.2.3 on 2025-07-30 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0002_bradley_name_destroyer_name_f18_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirDefenseArtillery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArleighBurkeClassDestroyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='B52',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bomber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C17',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='C5',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoAircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='E3',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EA18GGrowler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='F15',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='F22',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='F35',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='F35CLightningII',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FA18EFSuperHornet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldArtillery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FighterAircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Infantry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ISRAircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='K10',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KC135',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LHAAmphibiousAssaultShip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MH60RSeahawk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MQ9',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefuelingAircraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='U2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USNavyAttackSubmarine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USNavyNuclearBallisticSubmarine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='USSGeraldRFord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('classification', models.CharField(choices=[('CARGO_AIRCRAFT', 'Cargo Aircraft'), ('C5', 'C-5 Galaxy'), ('C17', 'C-17 Globemaster'), ('BOMBER', 'Bomber'), ('B2', 'B-2 Spirit'), ('B52', 'B-52 Stratofortress'), ('FIGHTER_AIRCRAFT', 'Fighter Aircraft'), ('F35', 'F-35 Lightning II'), ('F22', 'F-22 Raptor'), ('F15', 'F-15 Eagle'), ('MQ9', 'MQ-9 Reaper'), ('REFUELING_AIRCRAFT', 'Refueling Aircraft'), ('K10', 'KC-10 Extender'), ('KC135', 'KC-135 Stratotanker'), ('ISR_AIRCRAFT', 'ISR Aircraft'), ('E3', 'E-3 Sentry'), ('U2', 'U-2 Dragon Lady'), ('FIELD_ARTILLERY', 'Field Artillery'), ('ARMOR', 'Armor'), ('ENGINEER', 'Engineer'), ('AIR_DEFENSE_ARTILLERY', 'Air Defense Artillery'), ('SUPPORT', 'Support'), ('USS_GERALD_R_FORD', 'USS Gerald R. Ford'), ('F_A18E_F_SUPER_HORNET', 'F/A-18E/F Super Hornet'), ('E_A18G_GROWLER', 'EA-18G Growler'), ('F_35C_LIGHTNING_II', 'F-35C Lightning II'), ('ARLEIGH_BURKE_CLASS_DESTROYER', 'Arleigh Burke-Class Destroyer'), ('US_NAVY_ATTACK_SUBMARINE', 'US Navy Attack Submarine'), ('US_NAVY_NUCLEAR_BALLISTIC_SUBMARINE', 'US Navy Nuclear Ballistic Submarine'), ('MH_60R_SEAHAWK', 'MH-60R Seahawk'), ('LHA_AMPHIBIOUS_ASSAULT_SHIP', 'LHA Amphibious Assault Ship')], max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Bradley',
        ),
        migrations.DeleteModel(
            name='Destroyer',
        ),
        migrations.DeleteModel(
            name='F18',
        ),
    ]
