# Generated by Django 5.2.4 on 2025-07-25 23:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0002_bradley_name_destroyer_name_f18_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('categorization', models.CharField(max_length=10)),
                ('speed_mph', models.PositiveIntegerField()),
                ('supply_space', models.PositiveIntegerField()),
                ('supply_cost', models.PositiveIntegerField()),
                ('armor_type', models.CharField(max_length=50)),
                ('damage_type', models.CharField(max_length=50)),
                ('defense_mod', models.IntegerField()),
                ('health', models.IntegerField()),
                ('is_logi', models.BooleanField()),
                ('description', models.CharField(max_length=2500)),
            ],
        ),
        migrations.DeleteModel(
            name='Bradley',
        ),
        migrations.DeleteModel(
            name='Destroyer',
        ),
        migrations.DeleteModel(
            name='F18',
        ),
    ]
