# Generated by Django 5.2.4 on 2025-08-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0002_rename_supply_space_unit_max_supply_space_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TileInstance',
            new_name='LandmarkInstanceTile',
        ),
        migrations.AlterUniqueTogether(
            name='ability',
            unique_together={('unit', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='attack',
            unique_together={('unit', 'name')},
        ),
    ]
