# Generated by Django 5.2.4 on 2025-07-25 23:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0003_assettype_delete_bradley_delete_destroyer_delete_f18'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('x_position', models.PositiveIntegerField()),
                ('y_position', models.PositiveIntegerField()),
                ('team', models.CharField(choices=[('RED', 'Red'), ('BLUE', 'Blue'), ('NEUTRAL', 'Neutral')], max_length=10)),
                ('hitpoints', models.PositiveIntegerField()),
                ('primary_ammo', models.IntegerField()),
                ('secondary_ammo', models.IntegerField()),
                ('terciary_ammo', models.IntegerField()),
                ('supplies_count', models.IntegerField()),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.assettype')),
            ],
        ),
    ]
