# Generated by Django 5.2.4 on 2025-08-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0003_rename_tileinstance_landmarkinstancetile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attack',
            name='cost',
        ),
        migrations.AddConstraint(
            model_name='landmarkinstancetile',
            constraint=models.UniqueConstraint(fields=('tile', 'landmark_instance'), name='unique_tile_landmark_pair'),
        ),
        migrations.AddConstraint(
            model_name='roleinstance',
            constraint=models.UniqueConstraint(fields=('role', 'team'), name='unique_role_per_team'),
        ),
    ]
