# Generated by Django 5.2.4 on 2025-08-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0004_remove_attack_cost_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='roleinstance',
            name='unique_role_per_team',
        ),
    ]
