# Generated by Django 5.2.4 on 2025-08-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0005_remove_roleinstance_unique_role_per_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='cost',
        ),
        migrations.AddField(
            model_name='attack',
            name='cost',
            field=models.FloatField(default=25),
            preserve_default=False,
        ),
    ]
