# Generated by Django 5.2.4 on 2025-08-08 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0007_gameinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmarkinstance',
            name='team',
        ),
        migrations.RemoveField(
            model_name='roleinstance',
            name='team',
        ),
        migrations.RemoveField(
            model_name='unitinstance',
            name='team',
        ),
        migrations.AddField(
            model_name='landmarkinstance',
            name='game_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.gameinstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roleinstance',
            name='supply_points',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TeamInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victory_points', models.FloatField()),
                ('game_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.gameinstance')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.team')),
            ],
        ),
        migrations.AddField(
            model_name='landmarkinstance',
            name='team_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.teaminstance'),
        ),
        migrations.AddField(
            model_name='roleinstance',
            name='team_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.teaminstance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitinstance',
            name='team_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.teaminstance'),
            preserve_default=False,
        ),
    ]
