# Generated by Django 5.2.4 on 2025-08-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0008_remove_landmarkinstance_team_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ability',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attack',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tile',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ability',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_unit_ability_pair'),
        ),
        migrations.AddConstraint(
            model_name='attack',
            constraint=models.UniqueConstraint(fields=('unit', 'name'), name='unique_unit_attack_pair'),
        ),
        migrations.AddConstraint(
            model_name='teaminstance',
            constraint=models.UniqueConstraint(fields=('game_instance', 'team'), name='unique_game_team_pair'),
        ),
        migrations.AddConstraint(
            model_name='tile',
            constraint=models.UniqueConstraint(fields=('row', 'column'), name='unique_row_column_pair'),
        ),
    ]
