# Generated by Django 5.2.4 on 2025-08-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0009_alter_ability_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='branch',
            field=models.CharField(choices=[('Air Force', 'Air Force'), ('Army', 'Army'), ('Navy', 'Navy')], default='Air Force', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='is_logistic',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='domain',
            field=models.CharField(choices=[('Ground', 'Ground'), ('Air', 'Air'), ('Sea', 'Sea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(choices=[('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy'), ('Structure', 'Structure')], max_length=20),
        ),
    ]
