# Generated by Django 5.2.4 on 2025-08-12 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0010_unit_branch_unit_is_logistic_alter_unit_domain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='roleinstance',
            constraint=models.UniqueConstraint(fields=('team_instance', 'user'), name='unique_team_user_pair'),
        ),
    ]
