# Generated by Django 5.2.4 on 2025-08-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0011_alter_roleinstance_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinstance',
            name='supply_points',
            field=models.FloatField(default=0),
        ),
    ]
