# Generated by Django 5.2.4 on 2025-08-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0012_alter_roleinstance_supply_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminstance',
            name='victory_points',
            field=models.FloatField(default=0),
        ),
    ]
