# Generated by Django 5.2.4 on 2025-08-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0013_alter_teaminstance_victory_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='access_level',
        ),
        migrations.AddField(
            model_name='role',
            name='branch',
            field=models.CharField(blank=True, choices=[('Army', 'Army'), ('Air Force', 'Air Force'), ('Navy', 'Navy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='is_chief_of_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_logistics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_operations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_vice_commander',
            field=models.BooleanField(default=False),
        ),
    ]
