# Generated by Django 5.2.4 on 2025-08-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0014_remove_role_access_level_role_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='branch',
        ),
        migrations.AddField(
            model_name='unit',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UnitBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.branch')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.unit')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('unit', 'branch'), name='unique_unit_branch')],
            },
        ),
    ]
