# Generated by Django 5.2.4 on 2025-08-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0015_branch_remove_role_branch_unit_cost_unitbranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='branch',
        ),
        migrations.AddField(
            model_name='role',
            name='branch',
            field=models.CharField(blank=True, choices=[('Army', 'Army'), ('Air Force', 'Air Force'), ('Navy', 'Navy')], max_length=20, null=True),
        ),
    ]
