# Generated by Django 5.2.4 on 2025-08-18 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0016_remove_unit_branch_role_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.branch'),
        ),
    ]
