# Generated by Django 5.2.4 on 2025-08-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0017_alter_role_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='branches',
            field=models.ManyToManyField(through='wargamelogic.UnitBranch', to='wargamelogic.branch'),
        ),
    ]
