# Generated by Django 5.2.4 on 2025-08-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0001_squashed_0019_alter_ability_description_alter_attack_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='roleinstance',
            name='team_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.teaminstance'),
        ),
        migrations.AlterField(
            model_name='unitinstance',
            name='supply_count',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unitinstance',
            name='team_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.teaminstance'),
        ),
    ]
