# Generated by Django 5.2.3 on 2025-08-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0020_alter_attack_cost_alter_roleinstance_team_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
