# Generated by Django 5.2.4 on 2025-08-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0020_alter_attack_cost_alter_roleinstance_team_instance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'abilities'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'branches'},
        ),
        migrations.AlterModelOptions(
            name='unitbranch',
            options={'verbose_name_plural': 'unit branches'},
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
