# Generated by Django 5.2.4 on 2025-09-06 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0021_alter_ability_options_alter_branch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInstanceRolePoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_points', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='roleinstance',
            name='unique_team_user_pair',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='max_supply_space',
            new_name='max_supply_points',
        ),
        migrations.RenameField(
            model_name='unitinstance',
            old_name='supply_count',
            new_name='supply_points',
        ),
        migrations.RemoveField(
            model_name='roleinstance',
            name='supply_points',
        ),
        migrations.AddConstraint(
            model_name='roleinstance',
            constraint=models.UniqueConstraint(fields=('user', 'team_instance'), name='unique_user_team_instance_pair'),
        ),
        migrations.AddField(
            model_name='teaminstancerolepoints',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.role'),
        ),
        migrations.AddField(
            model_name='teaminstancerolepoints',
            name='team_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wargamelogic.teaminstance'),
        ),
        migrations.AddConstraint(
            model_name='teaminstancerolepoints',
            constraint=models.UniqueConstraint(fields=('team_instance', 'role'), name='unique_team_instance_role_pair'),
        ),
    ]
