# Generated by Django 5.2.4 on 2025-09-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0022_teaminstancerolepoints_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminstancerolepoints',
            options={'verbose_name_plural': 'team instance role points'},
        ),
    ]
