# Generated by Django 5.2.4 on 2025-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0023_alter_teaminstancerolepoints_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleinstance',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
