# Generated by Django 5.2.4 on 2025-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0024_roleinstance_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='icon',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
