# Generated by Django 5.2.4 on 2025-09-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0025_unit_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
