# Generated by Django 5.2.4 on 2025-09-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wargamelogic', '0026_gameinstance_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameinstance',
            name='turn_finish_time',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
